Website/Controllers/StatisticController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using PagedList;
using Website.DAL.Entities;
using Website.Models;

namespace Website.Controllers
{
	public class StatisticController : Controller
	{
		private readonly DbContext _dbContext;

		public StatisticController(DbContext dbContext)
		{
			_dbContext = dbContext;
		}

		// GET: Statistics
		public async Task<ActionResult> Index(int? page)
		{
			var statSet = _dbContext.Set<GameStatistic>();

			var totalGamesPlayed = await _dbContext.Set<GameStatistic>().CountAsync();

			var highestScore = await statSet.OrderByDescending(x => x.FinalScore)
				.Select(x => new ScoreViewModel { User = x.User.DisplayName ?? "Anonymous", Score = x.FinalScore, Date = x.GameEndTime })
				.FirstAsync();

			var lowestScore = await statSet.OrderBy(x => x.FinalScore)
				.Select(x => new ScoreViewModel { User = x.User.DisplayName ?? "Anonymous", Score = x.FinalScore, Date = x.GameEndTime })
				.FirstAsync();

			var latestScores = await new TaskFactory().StartNew(() => statSet
				.OrderByDescending(x => x.GameEndTime)
				.Select(x => new ScoreViewModel {User = x.User.DisplayName ?? "Anonymous", Score = x.FinalScore, Date = x.GameEndTime})
				.ToPagedList(page ?? 1, 10));

			var summaryViewModel = new StatisticSummaryViewModel
			{
				TotalGamesPlayed = totalGamesPlayed,
				HighestScore = highestScore,
				LowestScore = lowestScore,
				Scores = latestScores
			};

			return View(summaryViewModel);
		}
	}
}

Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Yahtzee", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("How to Play", "HowToPlay", "Home")</li>
                    <li>@Html.ActionLink("Statistics", "Index", "Statistic")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Nelson Wells</p>
            <p><a href="http://forum.thegamecreators.com/?m=forum_view&t=172821&b=1">Images from David Gervais</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <script src="~/signalr/hubs"></script>
    @RenderSection("scripts", required: false)
    <script>
        $(function () {

            var disableRollButton = function () {
                $("#roll_dice").prop("disabled", true);
            };

            var disableScoreButtons = function () {
                $("#score-card tr td button").prop("disabled", true);
            };

            var enableScoreButtons = function () {
                $("#score-card tr td button").prop("disabled", false);
            }

            var disableHoldButtons = function () {
                $.each([0, 1, 2, 3, 4], function (index, value) {
                    $("#hold-" + value).prop("disabled", true);
                });
            }

            var enableHoldButtons = function () {
                $.each([0, 1, 2, 3, 4], function (index, value) {
                    $("#hold-" + value).prop("disabled", false);
                });
            }

            var setDiceToUnhold = function () {
                $.each([0, 1, 2, 3, 4], function (index, value) {
                    var sel = $("#hold-" + value);
                    sel.removeClass("active");
                    sel.removeClass("btn-success");
                    sel.text("Hold");
                });
            }

            var yahtzee = $.connection.yahtzeeHub;

            yahtzee.client.processRoll = function (data) {
                console.log(data);
                for (i = 0; i < 5; i++) {
                    $("#die_" + i).attr("src", "/Content/Images/R_Dice_" + data.dice[i] + ".png");
                }
                if (data.isFinal) {
                    disableHoldButtons();
                    $("#roll-message").text("You've rolled " + data.rollCount + " times and that's your last roll this turn. Take a score.")
                }
                else {
                    enableScoreButtons();
                    enableHoldButtons();
                    $("#roll-message").text("You've rolled " + data.rollCount + " times.")
                }
            };

            yahtzee.client.setUpper = function (data) {
                $("#take-" + data.upperNum.toString()).replaceWith(data.score);
                if (data.isUpperSectionComplete) {
                    $("#upper-section-score").html("<b>" + data.upperSectionScore + "</b>");
                    $("#upper-section-bonus").html(data.upperSectionBonus);
                    $(".upper-section-total").html("<b>" + data.upperSectionTotal + "</b>");
                }

                disableScoreButtons();
                disableHoldButtons();
                setDiceToUnhold();
                if (data.isScoreSheetComplete) {
                    $("#grand-total").html("<b>" + data.grandTotal + "</b>");
                    $("#roll-message").text("The game is over. Your grand total is " + data.grandTotal + " points!")
                    disableRollButton();
                }
                else {
                    $("#roll-message").text("You've rolled 0 times.")
                }
            };

            yahtzee.client.setLower = function (data) {
                $("#" + data.name).replaceWith(data.score);
                if (data.isLowerSectionComplete) {
                    $("#lower-section-total").html("<b>" + data.lowerSectionTotal + "</b>");
                }

                disableScoreButtons();
                disableHoldButtons();
                setDiceToUnhold();
                if (data.isScoreSheetComplete) {
                    $("#grand-total").html("<b>" + data.grandTotal + "</b>");
                    $("#roll-message").text("The game is over. Your grand total is " + data.grandTotal + " points!")
                    disableRollButton();
                }
                else {
                    $("#roll-message").text("You've rolled 0 times.")
                }

            };

            yahtzee.client.disableHoldButtons = function () {
                disableHoldButtons();
            };

            yahtzee.client.toggleHoldDie = function (data) {
                var sel = $("#hold-" + data.index);
                if (data.dieState == "Held") {
                    sel.addClass("active");
                    sel.addClass("btn-success");
                    sel.text("Held");
                }
                else {
                    sel.removeClass("active");
                    sel.removeClass("btn-success");
                    sel.text("Hold");
                }
            };

            $.connection.hub.start().done(function () {
                $("#roll_dice").click(function () {
                    yahtzee.server.rollDice();
                });

                $.each([1, 2, 3, 4, 5, 6], function (index, value) {
                    $("#take-" + value.toString()).click(function () {
                        yahtzee.server.takeUpper(value);
                    });
                });

                $.each([0, 1, 2, 3, 4], function (index, value) {
                    $("#hold-" + value).click(function () {
                        yahtzee.server.toggleHoldDie(value)
                    });
                });

                var lowerItems = ["threeofakind", "fourofakind", "fullhouse", "smallstraight", "largestraight", "yahtzee", "chance"];
                $.each(lowerItems, function (index, value) {
                    $("#" + value).click(function () {
                        yahtzee.server.takeLower(value);
                    });
                });
            });
        });
    </script>

</body>
</html>